"""参考文献输出：BibTeX 条目 + Markdown 参考文献表。"""

from __future__ import annotations

import re
from typing import Dict, List, Sequence

# BibTeX 中需要转义的字符
_BIB_ESCAPE = {
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def _escape(text: str) -> str:
    if not text:
        return ""
    out = []
    for ch in str(text):
        out.append(_BIB_ESCAPE.get(ch, ch))
    return "".join(out).replace("\\\\", "\\")


def _last_name(author: str) -> str:
    author = (author or "").strip()
    if not author:
        return "anon"
    if "," in author:
        return author.split(",")[0].strip()
    return author.split()[-1]


def make_cite_key(paper: dict, used: set) -> str:
    """生成唯一的 BibTeX citation key：作者姓+年份+标题首个实词。"""
    authors = paper.get("authors") or []
    last = re.sub(r"[^A-Za-z]", "", _last_name(authors[0]) if authors else "anon").lower() or "anon"
    year = str(paper.get("year") or "nd")

    stop = {"a", "an", "the", "on", "of", "in", "for", "to", "and", "with", "towards", "via"}
    words = re.findall(r"[A-Za-z]+", paper.get("title") or "")
    word = next((w.lower() for w in words if w.lower() not in stop and len(w) > 2), "untitled")

    base = f"{last}{year}{word}"
    key, suffix = base, 1
    while key in used:
        key = f"{base}{chr(ord('a') + suffix - 1)}"
        suffix += 1
    used.add(key)
    return key


def _entry_type(paper: dict) -> str:
    source = paper.get("source", "")
    venue = (paper.get("venue") or "").lower()
    if source == "arxiv" or "arxiv" in venue or "preprint" in venue:
        return "misc"
    if any(k in venue for k in ("conference", "proceedings", "workshop", "symposium")):
        return "inproceedings"
    return "article"


def to_bibtex_entry(paper: dict, key: str) -> str:
    etype = _entry_type(paper)
    fields: List[tuple] = [
        ("title", _escape(paper.get("title"))),
        ("author", _escape(" and ".join(paper.get("authors") or []))),
        ("year", str(paper.get("year") or "")),
    ]

    venue = paper.get("venue") or ""
    if etype == "inproceedings":
        fields.append(("booktitle", _escape(venue)))
    elif etype == "article" and venue:
        fields.append(("journal", _escape(venue)))
    elif etype == "misc":
        arxiv_id = paper["paper_id"][6:] if paper.get("paper_id", "").startswith("arxiv:") else ""
        if arxiv_id:
            fields.append(("eprint", arxiv_id))
            fields.append(("archivePrefix", "arXiv"))
        fields.append(("howpublished", _escape(venue or "Preprint")))

    if paper.get("doi"):
        fields.append(("doi", paper["doi"]))
    if paper.get("url"):
        fields.append(("url", paper["url"]))

    body = ",\n".join(f"  {k} = {{{v}}}" for k, v in fields if v)
    return f"@{etype}{{{key},\n{body}\n}}"


def build_bibtex(papers: Sequence[dict]) -> tuple[str, Dict[str, str]]:
    """生成 .bib 文件内容。

    Returns:
        (bibtex 文本, {paper_id: cite_key})
    """
    used: set = set()
    entries, mapping = [], {}
    for paper in papers:
        key = make_cite_key(paper, used)
        mapping[paper["paper_id"]] = key
        entries.append(to_bibtex_entry(paper, key))
    header = (
        "% Generated by lit-review-agent\n"
        "% 仅收录检索到的公开元数据，PDF 全文仅限 OA 副本\n\n"
    )
    return header + "\n\n".join(entries) + "\n", mapping


def format_authors_inline(authors: Sequence[str], max_n: int = 3) -> str:
    authors = [a for a in authors if a]
    if not authors:
        return "Anon."
    if len(authors) <= max_n:
        return ", ".join(authors)
    return ", ".join(authors[:max_n]) + " et al."


def build_reference_list(
    papers: Sequence[dict],
    numbering: Dict[str, int],
    cite_keys: Dict[str, str] | None = None,
) -> str:
    """生成 Markdown 参考文献表（按引用编号排序）。"""
    ordered = sorted(
        [p for p in papers if p["paper_id"] in numbering],
        key=lambda p: numbering[p["paper_id"]],
    )
    lines = []
    for paper in ordered:
        idx = numbering[paper["paper_id"]]
        authors = format_authors_inline(paper.get("authors") or [])
        year = paper.get("year") or "n.d."
        title = paper.get("title") or "(untitled)"
        venue = paper.get("venue") or ""
        bits = [f"**[{idx}]** {authors} ({year}). *{title}*."]
        if venue:
            bits.append(f"{venue}.")
        if paper.get("citation_count"):
            bits.append(f"被引 {paper['citation_count']}.")
        if paper.get("doi"):
            bits.append(f"DOI: [{paper['doi']}](https://doi.org/{paper['doi']})")
        elif paper.get("url"):
            bits.append(f"[链接]({paper['url']})")
        if cite_keys and paper["paper_id"] in cite_keys:
            bits.append(f"`{cite_keys[paper['paper_id']]}`")
        lines.append(" ".join(bits))
    return "\n\n".join(lines)
